### ISSUE TITLE
Références bibliographiques cliquables

### ISSUE THREAD

**Issue by ipante** [Clamclim/SimulateurEntretien#3]
L'injection des références est excellent et la quantité d'informations adaptée. Rendez les références bibliographiques cliquables dans les info-bulles, en envoyant vers un target blank (autre page).

**Comment by Clamclim** [comment]
Est-ce que cela est aussi nécessaire pour les références qu'on ne peut pas trouver en ligne ?

**Comment by ipante** [comment]
Non, je ne pense pas. A moins que vous ne trouviez une référence vers l'ouvrage Google Books, par exemple.

**Comment by Clamclim** [comment]
D'accord, on va laisser comme ça alors !
